#!/bin/sh
# cd /home/ivan/teacher/mit_archive
#this scripts change all the html files into txt(.htmtxt)
# The following file types are remains : '.*dat' '.*py' '.*srt' '.*M' '.*sldprt' '.*m'
pwd
find . -maxdepth 1 -mindepth 1 -type d | while read courseName
do
	cd $courseName
	pwd
	cd `find ./material -maxdepth 1 -mindepth 1 -type d`/contents
	html2text ../START.htm > ../START.htmtxt
	html2text ./index.htm > ./index.htmtxt

	find . -maxdepth 1 -mindepth 1 -type d | while read folder
	do
		cd $folder
		find . -maxdepth 1 -mindepth 1 -name '*.htm' | while read fileName
		do
			echo '---->'$fileName
			html2text $fileName > `echo $fileName | sed 's/.htm/.htmtxt/g'`
		done
		cd ..
	done

	cd ../../../..
	
done
pwd
