#!/bin/sh
# cd /home/ivan/teacher/mit_archive
# this scripts unzip the material.zip file, and change all the pdf files into txt(.pdftxt)

pwd
find . -maxdepth 1 -mindepth 1 -type d | while read courseName
do
	cd $courseName
	pwd
	rm -rf ./material
	unzip -o -d material ./material.zip | grep 'silent' 
	cd `find ./material -maxdepth 1 -mindepth 1 -type d`/contents
	find . -maxdepth 1 -mindepth 1 -type d | while read folder
	do
		cd $folder
		find . -maxdepth 1 -mindepth 1 -name '*.pdf' | while read fileName
		do
			pdf2txt $fileName > `echo $fileName | sed 's/.pdf/.pdftxt/g'`
		done
		cd ..
	done

	cd ../../../..
	
done
pwd
