#!/bin/sh
# cd /home/ivan/teacher/mit_archive

find . -maxdepth 1 -mindepth 1 -type d | while read courseName
do
	cd $courseName
	if [ "0" -eq `find . -maxdepth 1 -mindepth 1 -name 'material.zip' | wc -l` ]
	then
		pwd
	fi
	cd ..
	
done

