#!/bin/sh
# cd /home/ivan/teacher/mit_archive
# this file checks for each .pdf file, whether there exists .pdftxt file of same name
pwd
find . -maxdepth 1 -mindepth 1 -type d | while read courseName
do	
	echo $courseName
	cd $courseName/material
	cd `find . -maxdepth 1 -mindepth 1 -type d `/contents
	
	find . -maxdepth 1 -mindepth 1 -type d | while read folder
	do
		cd $folder
		find . -maxdepth 1 -mindepth 1 -name '*.pdf' | while read fileNamee
		do
			pdftxt=`echo $fileNamee | sed 's/.pdf/.pdftxt/g' | sed 's/\.\///g'`
			if [ "0" -eq `find . -maxdepth 1 -mindepth 1 -name $pdftxt | wc -l` ]
			then
				echo $pdftxt' is not found!'
				pwd
				ls
				echo '____________________________'
			fi	

		done
		cd ..
	done

	cd ../../../..
	
done
