function y=ps5p2_z1star;


global ALPHAX ALPHAZ ALPHA BETA DELTA ALPHATILDEZ B C X1STAR SELECT OPTIONS...
   THETA2LOWER THETA2UPPER THETA1STAR ZUNDERBAR ZUPPERBAR;

g=sqrt(1+(ALPHATILDEZ/ALPHAX))*stdn_inv(1-(C/B));
y=(sqrt(ALPHAX)/ALPHATILDEZ)*(g-stdn_inv(THETA1STAR))+THETA1STAR;

